### ISSUE TITLE
defquery / insert: IllegalArgumentException First argument to defn must be a symbol

### ISSUE THREAD

**Issue by mathiasp** [boutros/matsu#1]
Hi Petter,
I just started experimenting with matsu.

When I try 
(q/defquery [](q/insert-data
    %28URI.) [:om :title] "A new book"
    \; [:om :creator] "A.N.Other" .))
I get the error above. 

Is this a bug in matsu (tried 0.1.2 and 0.1.3-SNAPSHOT) or is there an error in this quere.

It's from the example, just wrapped in a defquery instead of a query, so I assume it should work...

Thanks, Mathias

**Comment by mathiasp** [comment]
Forget it. I tried to make a simple testcase, and since I'm too tired I forgot the query name :) I should probably stop...

I will ask again, I still have an error, but now I assume it's mine :)

thanks for matsu, it's fun playing around with!

/ Mathias

**Comment by boutros** [comment]
Hi!
Sorry late reply; somehow I missed this.

As you probably found out defquery is just a macro, the same as:

``` clojure
(def my-query
  (fn [my-var]
    (query
      (select *
        (where :s :p my-var)))))
```

I must admit that I no longer work on this repo, as I came to realize I that I don't build queries dynamically that often. Theese days I usually use this simple query-bank when working with SPARQL in clojure:
https://github.com/knakk/query-bank
