### ISSUE TITLE
Conditional outside a `where` clause

### ISSUE THREAD

**Issue by fgiasson** [boutros/matsu#2]
Hi!

Great job with this DSL. However, I am having issues with conditionals outside a where clause. In a `where` we can quote a pattern within a `if` statement for example, but it doesn't seem possible outside the scope of a `where` operator. For example, if I am trying to add a `order-by` operator depending some criterias using a `cond` or a `case`, I am getting all kind of errors. I tried different tricks without any good results. Right now, I have to concatenate the string at the end of what is produced by Matsu, which is sub-optimal.

Is this just a limitation of the DSL?

Note: tested with 0.1.2 & 0.1.3-SNAPSHOT

**Comment by fgiasson** [comment]
Here is an example. If I add this code after a `where` clause and within a `query`:

```
(case sort
  "title" (case sort-order
            "desc" (matsu/order-by-desc :prefLabel)
            "asc" (matsu/order-by-asc :prefLabel))
  "uri" (case sort-order
          "desc" (matsu/order-by-desc :article)
          "asc" (matsu/order-by-asc :article))
  "published" (case sort-order
                "desc" (matsu/order-by-desc :published)
                "asc" (matsu/order-by-asc :published)))
```

I am getting this error:

```
Caused by java.lang.IllegalArgumentException
   Duplicate case test constant: case
```

Somehow, case is evaluated such that it considers that multiple conditions are the same. `cond` has other errors and a series of when doesn't work neither...

I think that the conditions (cond, case, if, when...) break the compiler somehow.

**Comment by boutros** [comment]
Hi!
I'ts been a while since I worked on this, but I suspect its a limitation of the compiler. I regret to say that I don't plan to investigate this.

I no longer use this library myself, opting instead for a simple query-bank solution when I use SPARQL in Clojure:
https://github.com/knakk/query-bank

**Comment by fgiasson** [comment]
Ok good thanks!
